sudo: required
dist: xenial

language: python
python:
- '3.7'
cache: pip

services:
- docker

install:
  - pip install pipenv
  - pipenv install --dev --system --deploy --ignore-pipfile

before_script:
  - cookiecutter . --no-input
  - cd cookiecutter_drf
  - bash travis/before_install.sh

script: bash travis/test.sh
