version: '3.6'

x-web-environment:
  &web-environment
  environment:
    - PORT=8000
    - ENVIRONMENT_NAME=local_dev
    - USING_DOCKER_COMPOSE=true
    - DJANGO_SETTINGS_MODULE=config.settings.local
    - DJANGO_CONFIGURATION=Local
    - DJANGO_SECRET_KEY
    - DJANGO_ALLOWED_HOSTS
    - DJANGO_CORS_ORIGIN_WHITELIST
    - DJANGO_ADMIN_URL=real-admin
  build:
    context: ./
    dockerfile: Dockerfile.local
  volumes:
    - type: bind
      source: ./
      target: /code
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:9.6

  redis:
    image: redis:4.0.11

  web:
    <<: *web-environment
    restart: always
    image: web
    ports:
      - "8000:8000"
    command: >
      bash -c "
        python scripts/local/wait_for_postgres.py &&
        ./manage.py migrate &&
        ./manage.py runserver 0.0.0.0:8000
      "
